apiVersion: apps/v1
kind: Deployment
metadata:
  name: php_practice1
  labels:
    app: php_practice1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php_practice1
  template:
    metadata:
      labels:
        app: php_practice1
    spec:
      containers:
      - name: bookalbum
        image: sneha758/php_practice1:v1
        ports:
        - containerPort: 80
