apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-practice1
  labels:
    app: php-practice1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-practice1
  template:
    metadata:
      labels:
        app: php-practice1
    spec:
      containers:
      - name: php-practice1
        image: sneha758/php-practice1:v1
        ports:
        - containerPort: 80
